mod contact_cache;
mod settings;
mod simulation;

use crate::body::{Body, BodyId, StaticBody};
use crate::collision::{Contact, ContactKey};
use crate::geometry::{GeometryPoint, UnitVector};
use crate::joint::{DistanceJoint, MouseJoint, RopeJoint};
use crate::quantity::Length;
use alloc::vec::Vec;
use contact_cache::HotContacts;
use core::{fmt, iter::FusedIterator, slice};

pub use settings::{BroadPhase, GridBroadPhase, WorldSettings};
use simulation::BroadPhaseScratch;
pub use simulation::StepStats;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddBodyError {
    DuplicateId(BodyId),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddMouseJointError {
    BodyNotFound(BodyId),
    DuplicateBody(BodyId),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddJointError {
    BodyNotFound(BodyId),
    SameBody(BodyId),
    StaticPair(BodyId, BodyId),
    DuplicatePair(BodyId, BodyId),
}

/// Deterministic collection of classical rigid bodies.
///
/// Bodies remain sorted by their stable ID, which defines the canonical
/// collision-pair order used by the simulation.
#[derive(Debug, Clone)]
pub struct World {
    settings: WorldSettings,
    bodies: Vec<Body>,
    static_bodies: Vec<StaticBody>,
    active_contacts: Vec<ActiveContact>,
    mouse_joints: Vec<MouseJoint>,
    distance_joints: Vec<DistanceJoint>,
    rope_joints: Vec<RopeJoint>,
    broad_phase_scratch: BroadPhaseScratch,
    hot_contacts: Vec<HotContacts>,
}

/// Solver contact using direct indices into the world's body storage.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ActiveContact {
    pub(crate) body_a: usize,
    pub(crate) body_b: ContactBodyIndex,
    pub(crate) point: GeometryPoint,
    pub(crate) normal: UnitVector,
    pub(crate) penetration: Length,
    /// `key` also stores whether this point owns manifold position correction.
    pub(crate) key: ContactKey,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ContactBodyIndex {
    Dynamic(usize),
    Static(usize),
}

/// Allocation-free view of contacts produced by the most recent simulation step.
#[derive(Clone)]
pub struct Contacts<'a> {
    active: slice::Iter<'a, ActiveContact>,
    bodies: &'a [Body],
    static_bodies: &'a [StaticBody],
}

impl Iterator for Contacts<'_> {
    type Item = Contact;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        let active = self.active.next()?;
        Some(self.resolve(active))
    }

    #[inline(always)]
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.active.size_hint()
    }
}

impl DoubleEndedIterator for Contacts<'_> {
    #[inline]
    fn next_back(&mut self) -> Option<Self::Item> {
        let active = self.active.next_back()?;
        Some(self.resolve(active))
    }
}

impl ExactSizeIterator for Contacts<'_> {
    #[inline(always)]
    fn len(&self) -> usize {
        self.active.len()
    }
}

impl FusedIterator for Contacts<'_> {}

impl<'a, 'b> PartialEq<Contacts<'b>> for Contacts<'a> {
    fn eq(&self, other: &Contacts<'b>) -> bool {
        Iterator::eq(self.clone(), other.clone())
    }
}

impl Eq for Contacts<'_> {}

impl fmt::Debug for Contacts<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.debug_list().entries(self.clone()).finish()
    }
}

impl<'a> Contacts<'a> {
    #[inline(always)]
    fn resolve(&self, active: &ActiveContact) -> Contact {
        let body_b = match active.body_b {
            ContactBodyIndex::Dynamic(index) => self.bodies[index].id(),
            ContactBodyIndex::Static(index) => self.static_bodies[index].id(),
        };
        Contact {
            body_a: self.bodies[active.body_a].id(),
            body_b,
            point: active.point,
            normal: active.normal,
            penetration: active.penetration,
            key: active.key,
        }
    }
}

impl World {
    #[inline(always)]
    pub const fn new(settings: WorldSettings) -> Self {
        Self {
            settings,
            bodies: Vec::new(),
            static_bodies: Vec::new(),
            active_contacts: Vec::new(),
            mouse_joints: Vec::new(),
            distance_joints: Vec::new(),
            rope_joints: Vec::new(),
            broad_phase_scratch: BroadPhaseScratch::new(),
            hot_contacts: Vec::new(),
        }
    }

    /// Returns bodies in ascending ID order.
    #[inline(always)]
    pub fn bodies(&self) -> &[Body] {
        &self.bodies
    }

    #[inline(always)]
    pub const fn body_count(&self) -> usize {
        self.bodies.len()
    }

    /// Returns static bodies in ascending ID order.
    #[inline(always)]
    pub fn static_bodies(&self) -> &[StaticBody] {
        &self.static_bodies
    }

    #[inline(always)]
    pub const fn static_body_count(&self) -> usize {
        self.static_bodies.len()
    }

    /// Returns contacts generated by the most recently completed simulation step.
    ///
    /// The view remains valid until the next step or a structural body change.
    #[inline]
    pub fn contacts(&self) -> Contacts<'_> {
        Contacts {
            active: self.active_contacts.iter(),
            bodies: &self.bodies,
            static_bodies: &self.static_bodies,
        }
    }

    /// Returns mouse joints in ascending body-ID order.
    #[inline(always)]
    pub fn mouse_joints(&self) -> &[MouseJoint] {
        &self.mouse_joints
    }

    #[inline]
    pub fn mouse_joint(&self, body: BodyId) -> Option<&MouseJoint> {
        let index = self
            .mouse_joints
            .binary_search_by_key(&body, |joint| joint.body())
            .ok()?;
        Some(&self.mouse_joints[index])
    }

    #[inline]
    pub fn mouse_joint_mut(&mut self, body: BodyId) -> Option<&mut MouseJoint> {
        let index = self
            .mouse_joints
            .binary_search_by_key(&body, |joint| joint.body())
            .ok()?;
        self.wake_body(body);
        Some(&mut self.mouse_joints[index])
    }

    /// Returns distance joints in canonical ascending endpoint order.
    #[inline(always)]
    pub fn distance_joints(&self) -> &[DistanceJoint] {
        &self.distance_joints
    }

    #[inline]
    pub fn distance_joint(&self, body_a: BodyId, body_b: BodyId) -> Option<&DistanceJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .distance_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        Some(&self.distance_joints[index])
    }

    #[inline]
    pub fn distance_joint_mut(
        &mut self,
        body_a: BodyId,
        body_b: BodyId,
    ) -> Option<&mut DistanceJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .distance_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        self.wake_joint_bodies(key.0, key.1);
        Some(&mut self.distance_joints[index])
    }

    /// Returns rope joints in canonical ascending endpoint order.
    #[inline(always)]
    pub fn rope_joints(&self) -> &[RopeJoint] {
        &self.rope_joints
    }

    #[inline]
    pub fn rope_joint(&self, body_a: BodyId, body_b: BodyId) -> Option<&RopeJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .rope_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        Some(&self.rope_joints[index])
    }

    #[inline]
    pub fn rope_joint_mut(&mut self, body_a: BodyId, body_b: BodyId) -> Option<&mut RopeJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .rope_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        self.wake_joint_bodies(key.0, key.1);
        Some(&mut self.rope_joints[index])
    }

    #[inline]
    pub fn body(&self, id: BodyId) -> Option<&Body> {
        let index = self.bodies.binary_search_by_key(&id, Body::id).ok()?;
        Some(&self.bodies[index])
    }

    #[inline]
    pub fn body_mut(&mut self, id: BodyId) -> Option<&mut Body> {
        let index = self.bodies.binary_search_by_key(&id, Body::id).ok()?;
        Some(&mut self.bodies[index])
    }

    #[inline]
    pub fn static_body(&self, id: BodyId) -> Option<&StaticBody> {
        let index = self
            .static_bodies
            .binary_search_by_key(&id, StaticBody::id)
            .ok()?;
        Some(&self.static_bodies[index])
    }

    /// Inserts a body while preserving ascending ID order.
    pub fn add_body(&mut self, body: Body) -> Result<(), AddBodyError> {
        if self.static_body(body.id()).is_some() {
            return Err(AddBodyError::DuplicateId(body.id()));
        }
        match self.bodies.binary_search_by_key(&body.id(), Body::id) {
            Ok(_) => Err(AddBodyError::DuplicateId(body.id())),
            Err(index) => {
                self.bodies.insert(index, body);
                self.hot_contacts.insert(index, HotContacts::EMPTY);
                self.clear_contacts();
                Ok(())
            }
        }
    }

    /// Inserts a static body while preserving ascending ID order. IDs share
    /// one namespace with dynamic bodies because contacts expose only BodyId.
    pub fn add_static_body(&mut self, body: StaticBody) -> Result<(), AddBodyError> {
        if self.body(body.id()).is_some() {
            return Err(AddBodyError::DuplicateId(body.id()));
        }
        match self
            .static_bodies
            .binary_search_by_key(&body.id(), StaticBody::id)
        {
            Ok(_) => Err(AddBodyError::DuplicateId(body.id())),
            Err(index) => {
                self.static_bodies.insert(index, body);
                self.clear_contacts();
                Ok(())
            }
        }
    }

    pub fn remove_body(&mut self, id: BodyId) -> Option<Body> {
        let index = self.bodies.binary_search_by_key(&id, Body::id).ok()?;
        self.remove_joints_for_body(id);
        let body = self.bodies.remove(index);
        self.hot_contacts.remove(index);
        self.clear_contacts();
        Some(body)
    }

    /// Adds one mouse joint for a dynamic body.
    pub fn add_mouse_joint(&mut self, joint: MouseJoint) -> Result<(), AddMouseJointError> {
        if self.body(joint.body()).is_none() {
            return Err(AddMouseJointError::BodyNotFound(joint.body()));
        }
        match self
            .mouse_joints
            .binary_search_by_key(&joint.body(), |item| item.body())
        {
            Ok(_) => Err(AddMouseJointError::DuplicateBody(joint.body())),
            Err(index) => {
                self.mouse_joints.insert(index, joint);
                self.wake_body(joint.body());
                Ok(())
            }
        }
    }

    pub fn remove_mouse_joint(&mut self, body: BodyId) -> Option<MouseJoint> {
        let index = self
            .mouse_joints
            .binary_search_by_key(&body, |joint| joint.body())
            .ok()?;
        let joint = self.mouse_joints.remove(index);
        self.wake_body(body);
        Some(joint)
    }

    pub fn add_distance_joint(&mut self, joint: DistanceJoint) -> Result<(), AddJointError> {
        self.validate_joint_pair(joint.body_a(), joint.body_b())?;
        let key = (joint.body_a(), joint.body_b());
        match self
            .distance_joints
            .binary_search_by_key(&key, |item| (item.body_a(), item.body_b()))
        {
            Ok(_) => Err(AddJointError::DuplicatePair(key.0, key.1)),
            Err(index) => {
                self.distance_joints.insert(index, joint);
                self.wake_joint_bodies(key.0, key.1);
                Ok(())
            }
        }
    }

    pub fn remove_distance_joint(
        &mut self,
        body_a: BodyId,
        body_b: BodyId,
    ) -> Option<DistanceJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .distance_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        let joint = self.distance_joints.remove(index);
        self.wake_joint_bodies(key.0, key.1);
        Some(joint)
    }

    pub fn add_rope_joint(&mut self, joint: RopeJoint) -> Result<(), AddJointError> {
        self.validate_joint_pair(joint.body_a(), joint.body_b())?;
        let key = (joint.body_a(), joint.body_b());
        match self
            .rope_joints
            .binary_search_by_key(&key, |item| (item.body_a(), item.body_b()))
        {
            Ok(_) => Err(AddJointError::DuplicatePair(key.0, key.1)),
            Err(index) => {
                self.rope_joints.insert(index, joint);
                self.wake_joint_bodies(key.0, key.1);
                Ok(())
            }
        }
    }

    pub fn remove_rope_joint(&mut self, body_a: BodyId, body_b: BodyId) -> Option<RopeJoint> {
        let key = canonical_pair(body_a, body_b);
        let index = self
            .rope_joints
            .binary_search_by_key(&key, |joint| (joint.body_a(), joint.body_b()))
            .ok()?;
        let joint = self.rope_joints.remove(index);
        self.wake_joint_bodies(key.0, key.1);
        Some(joint)
    }

    pub fn remove_static_body(&mut self, id: BodyId) -> Option<StaticBody> {
        let index = self
            .static_bodies
            .binary_search_by_key(&id, StaticBody::id)
            .ok()?;
        self.remove_joints_for_body(id);
        let body = self.static_bodies.remove(index);
        self.clear_contacts();
        Some(body)
    }

    fn clear_contacts(&mut self) {
        self.active_contacts.clear();
        self.hot_contacts.fill(HotContacts::EMPTY);
    }

    fn validate_joint_pair(&self, body_a: BodyId, body_b: BodyId) -> Result<(), AddJointError> {
        if body_a == body_b {
            return Err(AddJointError::SameBody(body_a));
        }
        for id in [body_a, body_b] {
            if self.body(id).is_none() && self.static_body(id).is_none() {
                return Err(AddJointError::BodyNotFound(id));
            }
        }
        if self.body(body_a).is_none() && self.body(body_b).is_none() {
            return Err(AddJointError::StaticPair(body_a, body_b));
        }
        Ok(())
    }

    fn wake_body(&mut self, id: BodyId) {
        if let Ok(index) = self.bodies.binary_search_by_key(&id, Body::id) {
            self.bodies[index].state_mut().wake();
        }
    }

    fn wake_joint_bodies(&mut self, body_a: BodyId, body_b: BodyId) {
        self.wake_body(body_a);
        self.wake_body(body_b);
    }

    fn remove_joints_for_body(&mut self, id: BodyId) {
        for index in 0..self.distance_joints.len() {
            let joint = self.distance_joints[index];
            if joint.body_a() == id || joint.body_b() == id {
                self.wake_joint_bodies(joint.body_a(), joint.body_b());
            }
        }
        for index in 0..self.rope_joints.len() {
            let joint = self.rope_joints[index];
            if joint.body_a() == id || joint.body_b() == id {
                self.wake_joint_bodies(joint.body_a(), joint.body_b());
            }
        }
        self.mouse_joints.retain(|joint| joint.body() != id);
        self.distance_joints
            .retain(|joint| joint.body_a() != id && joint.body_b() != id);
        self.rope_joints
            .retain(|joint| joint.body_a() != id && joint.body_b() != id);
    }
}

#[inline(always)]
fn canonical_pair(a: BodyId, b: BodyId) -> (BodyId, BodyId) {
    if a <= b {
        (a, b)
    } else {
        (b, a)
    }
}

impl Default for World {
    fn default() -> Self {
        Self::new(WorldSettings::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::body::{BodyState, Material};
    use crate::collider::Circle;
    use crate::quantity::{
        Angle, AngularVelocity, Force, Length, LinearAcceleration, LinearVelocity, Mass, Position,
    };
    use crate::transform::Transform;

    fn circle_body(id: u64) -> Body {
        Body::dynamic(
            BodyId::new(id),
            Circle::new(Length::from_meters(0.5).unwrap()).unwrap(),
            Mass::ONE,
            Material::INELASTIC,
            BodyState::new(
                Transform::new(Position::ZERO, Angle::ZERO),
                LinearVelocity::ZERO,
                AngularVelocity::ZERO,
            ),
        )
    }

    fn world() -> World {
        World::new(WorldSettings::new(LinearAcceleration::ZERO))
    }

    fn static_circle(id: u64, x: f64) -> StaticBody {
        StaticBody::new(
            BodyId::new(id),
            Transform::new(Position::from_meters(x, 0.0).unwrap(), Angle::ZERO),
            Circle::new(Length::from_meters(0.1).unwrap()).unwrap(),
            Material::INELASTIC,
        )
    }

    fn distance_joint(a: u64, b: u64) -> DistanceJoint {
        DistanceJoint::new(
            BodyId::new(a),
            Position::ZERO,
            BodyId::new(b),
            Position::ZERO,
            Length::from_meters(1.0).unwrap(),
            Force::from_newtons(10.0).unwrap(),
        )
    }

    fn rope_joint(a: u64, b: u64) -> RopeJoint {
        RopeJoint::new(
            BodyId::new(a),
            Position::ZERO,
            BodyId::new(b),
            Position::ZERO,
            Length::from_meters(1.0).unwrap(),
            Force::from_newtons(10.0).unwrap(),
        )
    }

    #[test]
    fn active_contact_storage_remains_compact() {
        assert_eq!(core::mem::size_of::<ActiveContact>(), 48);
    }

    #[test]
    fn bodies_are_sorted_and_found_by_stable_id() {
        let mut world = world();
        world.add_body(circle_body(9)).unwrap();
        world.add_body(circle_body(2)).unwrap();

        assert_eq!(world.bodies()[0].id(), BodyId::new(2));
        assert_eq!(world.bodies()[1].id(), BodyId::new(9));
        assert_eq!(world.body(BodyId::new(9)).unwrap().id(), BodyId::new(9));

        assert_eq!(
            world.remove_body(BodyId::new(2)).unwrap().id(),
            BodyId::new(2)
        );
        assert!(world.body(BodyId::new(2)).is_none());
    }

    #[test]
    fn hot_contact_storage_tracks_body_lifecycle() {
        let mut world = world();
        world.add_body(circle_body(9)).unwrap();
        world.add_body(circle_body(2)).unwrap();
        assert_eq!(world.hot_contacts.len(), world.bodies.len());

        world.remove_body(BodyId::new(2)).unwrap();
        assert_eq!(world.hot_contacts.len(), world.bodies.len());
        assert_eq!(world.hot_contacts[0], HotContacts::EMPTY);
    }

    #[test]
    fn public_contacts_resolve_ids_and_are_cleared_before_indices_shift() {
        let mut world = world();
        world.add_body(circle_body(9)).unwrap();
        world.add_body(circle_body(2)).unwrap();

        assert_eq!(world.step().contacts, 1);
        let mut contacts = world.contacts();
        assert_eq!(contacts.len(), 1);
        let contact = contacts.next().unwrap();
        assert_eq!(
            (contact.body_a, contact.body_b),
            (BodyId::new(2), BodyId::new(9))
        );

        world.add_body(circle_body(1)).unwrap();
        assert_eq!(world.contacts().len(), 0);
    }

    #[test]
    fn duplicate_body_id_is_rejected() {
        let mut world = world();
        world.add_body(circle_body(7)).unwrap();

        assert_eq!(
            world.add_body(circle_body(7)),
            Err(AddBodyError::DuplicateId(BodyId::new(7)))
        );
    }

    #[test]
    fn dynamic_and_static_bodies_share_id_namespace() {
        let mut world = world();
        world.add_body(circle_body(7)).unwrap();
        let static_body = StaticBody::new(
            BodyId::new(7),
            Transform::IDENTITY,
            Circle::new(Length::from_meters(1.0).unwrap()).unwrap(),
            Material::INELASTIC,
        );

        assert_eq!(
            world.add_static_body(static_body),
            Err(AddBodyError::DuplicateId(BodyId::new(7)))
        );
    }

    #[test]
    fn mouse_joint_requires_a_unique_dynamic_body() {
        let mut world = world();
        let joint = MouseJoint::new(
            BodyId::new(7),
            Position::ZERO,
            Position::ZERO,
            Force::from_newtons(10.0).unwrap(),
        );

        assert_eq!(
            world.add_mouse_joint(joint),
            Err(AddMouseJointError::BodyNotFound(BodyId::new(7)))
        );
        world.add_body(circle_body(7)).unwrap();
        world.add_mouse_joint(joint).unwrap();
        assert_eq!(
            world.add_mouse_joint(joint),
            Err(AddMouseJointError::DuplicateBody(BodyId::new(7)))
        );
        assert_eq!(world.mouse_joint(BodyId::new(7)), Some(&joint));

        world.remove_body(BodyId::new(7)).unwrap();
        assert!(world.mouse_joints().is_empty());
    }

    #[test]
    fn two_body_joint_rejects_every_invalid_pair_kind() {
        let mut world = world();
        world.add_body(circle_body(1)).unwrap();
        world.add_static_body(static_circle(2, 2.0)).unwrap();
        world.add_static_body(static_circle(3, 3.0)).unwrap();

        assert_eq!(
            world.add_distance_joint(distance_joint(1, 1)),
            Err(AddJointError::SameBody(BodyId::new(1)))
        );
        assert_eq!(
            world.add_distance_joint(distance_joint(1, 9)),
            Err(AddJointError::BodyNotFound(BodyId::new(9)))
        );
        assert_eq!(
            world.add_rope_joint(rope_joint(2, 3)),
            Err(AddJointError::StaticPair(BodyId::new(2), BodyId::new(3)))
        );

        world.add_distance_joint(distance_joint(2, 1)).unwrap();
        assert_eq!(
            world.add_distance_joint(distance_joint(1, 2)),
            Err(AddJointError::DuplicatePair(BodyId::new(1), BodyId::new(2)))
        );
    }

    #[test]
    fn two_body_joint_collections_support_full_lookup_lifecycle() {
        let mut world = world();
        world.add_body(circle_body(1)).unwrap();
        world.add_body(circle_body(3)).unwrap();
        world.add_static_body(static_circle(2, 2.0)).unwrap();

        world.add_distance_joint(distance_joint(3, 2)).unwrap();
        world.add_distance_joint(distance_joint(2, 1)).unwrap();
        world.add_rope_joint(rope_joint(3, 1)).unwrap();

        assert_eq!(world.distance_joints()[0].body_a(), BodyId::new(1));
        assert_eq!(world.distance_joints()[1].body_b(), BodyId::new(3));
        world
            .distance_joint_mut(BodyId::new(2), BodyId::new(1))
            .unwrap()
            .set_length(Length::from_meters(0.5).unwrap());
        assert_eq!(
            world
                .distance_joint(BodyId::new(1), BodyId::new(2))
                .unwrap()
                .length(),
            Length::from_meters(0.5).unwrap()
        );
        assert!(world
            .remove_rope_joint(BodyId::new(1), BodyId::new(3))
            .is_some());
        assert!(world.rope_joints().is_empty());

        world.remove_static_body(BodyId::new(2)).unwrap();
        assert!(world.distance_joints().is_empty());
    }

    #[test]
    fn removing_either_dynamic_endpoint_cleans_both_joint_types() {
        let mut world = world();
        world.add_body(circle_body(1)).unwrap();
        world.add_body(circle_body(2)).unwrap();
        world.add_distance_joint(distance_joint(1, 2)).unwrap();
        world.add_rope_joint(rope_joint(1, 2)).unwrap();

        world.remove_body(BodyId::new(2)).unwrap();

        assert!(world.distance_joints().is_empty());
        assert!(world.rope_joints().is_empty());
    }
}
